### ISSUE TITLE
`renderString` should insert resolved promise values

### ISSUE THREAD

**Issue by blakek** [gsandf/template-file#14]
Right now, we allow inserting data returned from a function.

**Current behavior:**

```javascript
const getUserDetails = () => ({ name: 'John Doe' })

renderString('{{ name }} is cool.', getUserDetails)
```

However, it'd be nice if this allowed promises to be specified.  This would allow async tasks to be run instead of requiring it all be done in advance.

**Proposed behavior:**

```javascript
const getUserDetails = async () => {
  const user = await getUserFromDatabase()
  return { name: user.name }
}

await renderString('{{ name }} is cool.', getUserDetails)
```

This would be a major-version API change because `renderString` will return a promise instead of a string.

**Comment by aichbauer** [comment]
If I understand this right, `getUserFromDatabase()` should return a resolved Promise. And if this already works:

```js
const getUserDetails = () => ({ name: 'John Doe' });

renderString('{{ name }} is cool.', getUserDetails());
```

so this will also work: 

```js
const getUserDetails = async () => {
  const user = await getUserFromDatabase();
  return { name: user.name };
};

renderString('{{ name }} is cool.', await getUserDetails());
```

Do I miss something?

**Comment by blakek** [comment]
@aichbauer you're absolutely right, that's an incorrect example.  This issue was created to have `renderString` resolve arguments if the argument is an unresolved Promise (the example incorrectly shows `await`-ing the Promise).  However, after taking a second look, it's really unnecessary.  Something like this could be done instead:

```javascript
  const asyncTasks = [
    getUserDetails(),
    getUserConfiguration(),
    otherAsyncStuff()
  ];

  renderString('{{ name }}', ...(await Promise.all(asyncTasks)));
```

Thanks!
