### ISSUE TITLE
Running with node older than 14 has problem

### ISSUE THREAD

**Issue by bingtimren** [gsandf/template-file#45]
Running template-file with older node versions (<=12) has a problem:

```
$ npx  template-file
Cannot find module 'fs/promises'
```

This is caused by: [https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly](https://stackoverflow.com/questions/64725249/fs-promises-api-in-typescript-not-compiling-in-javascript-correctly)

I'm submitting a pull request to make it work for the older node versions.

**Comment by blakek** [comment]
Thanks for the PR! This fix is released in v4.0.2.
