### ISSUE TITLE
Dependency meow security vulnerability

### ISSUE THREAD

**Issue by kkmavr** [gsandf/template-file#57]
There is a vulnerability in the trim-newlines library used.
template-file>meow 8.0.0 >trim-newlines 3.0.0

[GHSA-7p7h-4mm5-852v](https://github.com/advisories/GHSA-7p7h-4mm5-852v)

Is there a change to update meow to v10.0.1 or a later one, so that it ends up using trim-newlines v4.0.1 which is the patched version?

**Comment by blakek** [comment]
The vulnerable code isn't used by this package, but we do plan to update.

The issue is upgrading to meow v10 (and p-limit v4) requires a new build system due to the packages being [pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) now.

**Comment by blakek** [comment]
This is resolved in v6.0.0 where `meow` is removed. Thanks!
