### ISSUE TITLE
Getting: "Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined ...." error 

### ISSUE THREAD

**Issue by ieazie** [gsandf/template-file#60]
This might be a problem with my setup, however, i keep getting the below error:

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/john.doe/Documents/Projects/cli/node_modules/template-file/package.json imported from /Users/john.doe/Documents/Projects/cli/lib/config-generator.js

Please could you help point me in the right direction on resolving this?

**Comment by ieazie** [comment]
I fixed this by updating the template-file package.json in my node_modules, I changed the exports **from**:

```
"exports": {
    "required": "dist/index.js"
  },
```
**to** 

```
  "exports": {
    ".": "./dist/index.js"
  },
```
However, I think this is not an actual fix, I could use an assist with a real fix.
I use node **v14.13.1**

**Comment by techfort** [comment]
hey @ieazie how come you closed the issue? i'm getting the same error

**Comment by blakek** [comment]
We haven't seen this before, but after reading I _think_ I see a way we could test something.

Could one of you remove the `exports` object from `node_modules/template-file/package.json` in your project and let me know if it runs?

```js
// Before
"main": "dist/index.js",
"exports": {
  "require": "./dist/index.js"
},
"description": "🔀 Replace {{ variables }} in all your files",

// After
"main": "dist/index.js",
"description": "🔀 Replace {{ variables }} in all your files",
```

Also, are you using any tooling to transpile to an ES5 target or Node.js CommonJS? Just asking because it seems some build tool sees the `exports` but doesn't find what it's looking for (e.g. `exports.import`).

**Comment by blakek** [comment]
Also, if you have a minimal example, that'd be perfect. It'd help us get this solved a bit sooner.

**Comment by ieazie** [comment]
> We haven't seen this before, but after reading I _think_ I see a way we could test something.
> 
> Could one of you remove the `exports` object from `node_modules/template-file/package.json` in your project and let me know if it runs?
> 
> ```js
> // Before
> "main": "dist/index.js",
> "exports": {
>   "require": "./dist/index.js"
> },
> "description": "🔀 Replace {{ variables }} in all your files",
> 
> // After
> "main": "dist/index.js",
> "description": "🔀 Replace {{ variables }} in all your files",
> ```
> 
> Also, are you using any tooling to transpile to an ES5 target or Node.js CommonJS? Just asking because it seems some build tool sees the `exports` but doesn't find what it's looking for (e.g. `exports.import`).

I was able to resolve it as below:

````
// Before
"main": "dist/index.js",
"exports": {
  "require": "./dist/index.js"
},
"description": "🔀 Replace {{ variables }} in all your files",
````

````
// After
"main": "dist/index.js",
"exports": {
  ".": "./dist/index.js"
},
"description": "🔀 Replace {{ variables }} in all your files",
````
I suspect it may have something to do with my node version, I'm using version v14.13.1

**Comment by blakek** [comment]
Could you test version 6.0.1? This should be fixed!
